language: node_js

node_js:
- '9.5.0'

branches:
  only:
  - master

before_install:
- git submodule update --init --recursive
- ln theme.config.yml themes/Hacker/_config.yml
- npm install -g hexo-cli

install:
- npm install

script:
- hexo generate

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: public
  skip-cleanup: true
  keep-history: true