language: node_js

node_js:
- '9.5.0'

branches:
  only:
  - master

git:
  submodules: false

before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
- npm install -g hexo-cli

install:
- npm install

script:
- ln theme.config.yml themes/Hacker/_config.yml
- hexo generate

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: public
  skip-cleanup: true
  keep-history: true